
server.port=8080


# server.address=0.0.0.0

# Formato de salida de los logs
logging.level.org.springframework=INFO
logging.level.com.blackjack=DEBUG

# Configuración de MongoDB (si en el futuro conectas)
spring.data.mongodb.uri=mongodb://localhost:27017/blackjack

# Springdoc OpenAPI (Swagger) configuración básica
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

