spring:
  data:
    mongodb:
      uri: mongodb://admin:secret@mongo:27017/blackjack_db?authSource=admin

  datasource:
    url: jdbc:mysql://localhost:3307/blackjack
    username: root
    password: secret
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    org.springframework: INFO
    com.blackjack: DEBUG

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
